### ISSUE TITLE
Tooling: Create `ok pkg install` command

### ISSUE THREAD

**Issue by staticaland** [oslokommune/ok#124]
```[tasklist]
### Tasks
- [x] Phase out `ok get` command
- [x] Create `ok pkg install` command
- [ ] https://github.com/oslokommune/ok/issues/175
```

## Undecided

- What to name the package file?
  - `package.yml`
  - `Platefile.yml`
  - `.boilerplate.yml`

Could it be useful to include Boilerplate in the name?

## Inspiration

- `npm`
- `pip`
- `poetry`

## Decisions

| Consider                        | Decision | Why                                                                |
| ------------------------------- | -------- | ------------------------------------------------------------------ |
| Move vars to configuration (`package.yml`) file | 🟥       | Can't be used with regular Boilerplate CLI                                  |
| Use JSON                        | 🟥       | Boilerplate uses YAML                                              |
| Use YAML                        | 💚       | Same as Boilerplate, i.e. give users same UX for Boilerplate and `ok`. Not included in Go standard library.          |
| Use `go-yaml/yaml`              | 💚       | Decent library. Not updated in 2 years. Easy to replace if needed. |
| Use same variable names as Boilerplate and Git (`ref`) | 💚 | No better suggestions |
| Use pascal case in config | 💚 | Boilerplate uses pascal case because it's a Go convention. However, snake case is arguably easier to read. Search the web for the science. However, we choose to use same convention for both `Boilerplate` and `ok` (i.e. pascal case). Consider changing both to snake case. |
| Add this feature to Boilerplate itself | 🟥 | Too many unknowns |

## Config format

[Snake case](https://en.wikipedia.org/wiki/Snake_case):

```yml
template_url: app
ref: v1.0.0
output_folder: app-km
var_files:
  - file1.yml
  - file2.yml
```

[Camel case](https://developer.mozilla.org/en-US/docs/Glossary/Camel_case):

```yml
templateUrl: app
ref: v1.0.0
outputFolder: app-km
varFiles:
  - file1.yml
  - file2.yml
```

[Pascal case](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#pascal-case):

```yml
TemplateUrl: app
Ref: v1.0.0
OutputFolder: app-km
VarFiles:
  - file1.yml
  - file2.yml
```

**Comment by staticaland** [comment]
See https://atmos.tools/core-concepts/vendor/vendor-manifest

**Comment by staticaland** [comment]
See https://terragrunt.gruntwork.io/docs/features/scaffold/

**Comment by falense** [comment]
Automatiske oppdateringer av Boilerplate templates fungerer nå. Mer om PoC finner man her: https://oslokommune.slack.com/archives/C018EFCSC4W/p1720528018620289?thread_ts=1720524630.871659&cid=C018EFCSC4W
