### ISSUE TITLE
Get GitHub token from keyring

### ISSUE THREAD

**Issue by staticaland** [oslokommune/ok#163]
Use [`zalando/go-keyring`](https://github.com/zalando/go-keyring) to retrieve tokens stored by the GitHub CLI. This library is used by the GitHub CLI for secure credential storage.

For more context, see: https://github.com/cli/cli/pull/7043

## Tasks

- [x] Add `zalando/go-keyring` dependency
- [x] Implement token retrieval using the library
- [x] Update existing code to use new retrieval method
- [x] Test compatibility with GitHub CLI stored tokens
